language: java
jdk:
  - oraclejdk8
python:
  - "3.7"
dist: trusty
env:
  - NODE_VERSION="8"
sudo: required
git:
  depth: false
addons:
  sonarcloud:
    organization: "orkunkocyigit-github"
before_install:
  - "nvm install $NODE_VERSION"
  - "npm update -g npm"
  - "npm ci"
  - "if [ '${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}' != 'master' ]; then npm run download:arm -- -s game -w 30 -y && npm run download:chara -- -s game -w 30 -y; fi"
script:
  - npm test
  - sonar-scanner
  - npm run production-build
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    repo: OrkunKocyigit/motocal-dev
    github_token: $GITHUB_DEV_TOKEN
    local_dir: dist
    on:
      all_branches: true
      condition: ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} != master