language: java
jdk:
  - oraclejdk8
dist: trusty
env:
  - NODE_VERSION="8"
sudo: required
git:
  depth: false
addons:
  sonarcloud:
    organization: "orkunkocyigit-github"
before_install:
  - "nvm install $NODE_VERSION"
  - "npm update -g npm"
  - "npm ci"
script:
  - npm test
  - sonar-scanner
  - npm run production-build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    all_branches: true
